### ISSUE TITLE
`trie_structure` algorithm

### ISSUE THREAD

**Issue by vikinatora** [LimeChain/java-host#242]
https://github.com/smol-dot/smoldot/blob/377fdf027862b3d39f65b6883bea0edb96208f7b/full-node/src/lib.rs#L862-L950
- [x] Implement algorithm that generates the `trie_structure`
- [x] Implement `trie_structure` methods that are necessary for the algorithm

Subtasks:
- #259 
- #260 
- [ ] Implement a `prettyPrint()` method or some sort of visualization for the strie structure, since inspecting the state from the debugger is not very helpful in figuring out what's wrong 😄

**Comment by David-Petrov** [comment]
Everything except the calculation of merkle values is already implemented (generally outlined, but **not tested**). The main bulk of remaining work is testing + all the necessary refactoring that will pop up for testability purposes. So this whole task depends on:
- [ ] #260 
- [ ] exhaustive testing + refactoring.
