### ISSUE TITLE
Merge the `jsonrpc4j` fix for the issue with `Spring Boot v3.x`

### ISSUE THREAD

**Issue by nistanimirov** [LimeChain/java-host#370]
1. Task description
This problem dates back to https://github.com/LimeChain/Fruzhin/issues/28 at which point no solution was available.  
  However, in the original issue [here](https://github.com/briandilley/jsonrpc4j/issues/303), it can be seen (as a most recent activity at the time of writing this), that [a PR](https://github.com/briandilley/jsonrpc4j/pull/312) has been opened to propose a fix in the original repo. Since the original is not being actively maintained, there's [a fork](https://github.com/Lendico/jsonrpc4j/pull/1) which merges this PR. 
  Investigate how this fix is applicable in [our fork](https://github.com/LimeChain/jsonrpc4j). 

2. Motivation
This is very significant since this dependency on `jsonrpc4j` is the reason we can't upgrade our Spring version, which in turn is the reason we're stuck on Java 17. Resolving this issue will untie our hands and help Fruzhin be updatable, hence not legacy 😄

**Comment by reneleonhardt** [comment]
@nistanimirov the PR has been merged and a new version 1.7 has been released in case you still need it 😄

**Comment by Zurcusa** [comment]
@reneleonhardt, I can't seem to find a 1.7 release of the original repository.
https://mvnrepository.com/artifact/com.github.briandilley.jsonrpc4j/jsonrpc4j
https://github.com/briandilley/jsonrpc4j/tags

Maybe they're planning on doing it soon. Will keep an eye on it.

PS. Found it here, https://central.sonatype.com/artifact/com.github.briandilley.jsonrpc4j/jsonrpc4j/1.7

**Comment by Zurcusa** [comment]
It seems like that the original repository still uses the `javax` namespace. Our fork has already migrated to the `jakarta` namespace.

**Comment by reneleonhardt** [comment]
I'm no maintainer, I couldn't find a realease or tag either, but I was happy that at least Maven Central shows it 😅
https://central.sonatype.com/artifact/com.github.briandilley.jsonrpc4j/jsonrpc4j/versions
I like mvnrepository, but they're not always up to date.

I already asked if updates would be allowed now, Spring 6 has a JDK 17 and Jakarta EE 9 baseline since 2022.
https://github.com/briandilley/jsonrpc4j/issues/330#issuecomment-2869120897

**Comment by briandilley** [comment]
Feel free to submit pull requests to jsonrpc4j

**Comment by adityakishore** [comment]
> It seems like that the original repository still uses the `javax` namespace. Our fork has already migrated to the `jakarta` namespace.

@Zurcusa, is this a public fork?
