### ISSUE TITLE
Implement async fetch functionality in the TeaVm Fruzhin project.

### ISSUE THREAD

**Issue by Zurcusa** [LimeChain/java-host#506]
In order to implement #494 and have decent performance we need the possibility to send async requests.

Find a way to implement that functionality (most probably via a fetch request). Thins to consider:

- Having a reusable representation (in the form of an object) for RPCRequests and RPCResponses.
- Having access to the response data in the Java code. Possible options might be using callbacks or the TeaVM `Promise` implementation `JSPromise`.

**Comment by nistanimirov** [comment]
#494
