### ISSUE TITLE
Implement Protocols

### ISSUE THREAD

**Issue by nistanimirov** [LimeChain/java-host#518]

**Comment by Zurcusa** [comment]
After researching the topic of substrate connect it became obvious that point 6. (vi) of the light client [requirements](https://spec.polkadot.network/sect-lightclient#sect-requirements-lightclient) is not a straightforward task. It's not obvious what is the desired outcome of the protocol implementation, nor what is supposed to be solved.

### **What is substrate connect?**
It is a way to connect with the polkadot chains directly from the browser without the need to start a node locally, nor configure a connection to an external node. More info can be found [here](https://substrate.io/developers/substrate-connect/).

### **What is the issue with implementing the @substrate/connect [connection extension protocol](https://github.com/paritytech/substrate-connect/tree/main/packages/connect-extension-protocol)?**
Substrate connect itself works with the light client web implementation of [smoldot](https://github.com/smol-dot/smoldot). In other words it cannot directly make use of Fruzhin as a light client and also it does not make much sense to have Fruzhin communicate with the smoldot instance that substrate connect would start in the browser.

### **What is the outcome of the research?**
After opening [this ticket](https://github.com/paritytech/substrate-connect/issues/2427) in the substrate connect repository it became clear that the connection extension protocol that is to be supported as per polkadot specs will soon be deprecated and should be substituted with [@substrate/discovery](https://github.com/paritytech/substrate-connect/tree/main/packages/discovery). I also had a discussion with a representative of the web 3 foundation who explained the need for the requirements like so:

> I think the necessity of substrate connect stemmed from the fact that most browsers natively do not support mulltiple p2p (wss) connections needed by the light client.

Considering we already support multiple peer connections we concluded that this is not a compulsory requirement for Fruzhin.

**Comment by ryanleecode** [comment]
We can add fruzhin as an option for the backing node if you guys want. i.e the user will be able to toggle between fruzhin and smoldot

**Comment by nistanimirov** [comment]
Hi @ryanleecode thanks for your feedback! We are looking into it so, please stay tuned for updates!
